# Change these first
owner: ninetydays # Your GitHub organization or username, where this repository lives
repo: Upptime # The name of this repository

sites:
  - name: new-loan
    url: https://90days.kr/
  - name: citron
    url: https://loan.90days.kr/

status-website:
# Add your custom domain name, or remove the `cname` line if you don't have a domain
# Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
#cname: demo.upptime.js.org
  apiBaseUrl: https://api.github.com
  baseUrl: /Upptime
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/ninetydays/Upptime
 